-- Auto-generated from schema-map-postgres.yaml (map@sha1:6D9B52237D942B2B3855FD0F5500331B935A7C62)
-- engine: postgres
-- table:  system_jobs

CREATE TABLE IF NOT EXISTS system_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type VARCHAR(100) NOT NULL,
  payload JSONB NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  retries INTEGER NOT NULL DEFAULT 0,
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at TIMESTAMPTZ(6) NULL,
  finished_at TIMESTAMPTZ(6) NULL,
  error TEXT NULL,
  unique_key_hash CHAR(64) NULL,
  unique_key_version VARCHAR(64) NULL,
  locked_until TIMESTAMPTZ(6) NULL,
  locked_by VARCHAR(100) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_system_jobs_version CHECK (version >= 0),
  CONSTRAINT chk_system_jobs_status CHECK (status IN ('pending','processing','done','failed')),
  CONSTRAINT chk_system_jobs_retries CHECK (retries >= 0)
);
