-- Auto-generated from schema-map-postgres.psd1 (map@mtime:2025-10-24T09:46:38Z)
-- engine: postgres
-- table:  system_jobs
CREATE TABLE IF NOT EXISTS system_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type VARCHAR(100) NOT NULL,
  payload JSONB NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  retries INTEGER NOT NULL DEFAULT 0,
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at TIMESTAMPTZ(6) NULL,
  finished_at TIMESTAMPTZ(6) NULL,
  error TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_system_jobs_status CHECK (status IN ('pending','processing','done','failed'))
);
